### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by fwcd** [georgewfraser/kotlin-language-server#1]
Support for the Gradle build tool would be really awesome.

**Comment by ajarara** [comment]
Do you mean building this project using gradle or having the kotlin language server support groovy as well?

**Comment by fwcd** [comment]
@alphor I mean having support for Gradle-based projects when using the server. Full Groovy support might not even be necessary as long as the dependencies can somehow be parsed.

Although I have considered opening a PR and implementing it myself, I can not promise that this will happen anytime soon.

**Comment by fwcd** [comment]
I have done quite some work and implemented (experimental) Gradle support myself and have also migrated this project to a Gradle-based build (which is a lot cleaner IMO) in [my fork of this repo](https://github.com/fwcd/kotlin-language-server).

Once the Gradle support is more mature I will open a pull request.

**Comment by fwcd** [comment]
Solved with #3
